import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
	resolve: {
		alias: {
			$lib: fileURLToPath(new URL("./src", import.meta.url)),
		},
	},
	test: {
		environment: "node",
		include: ["src/**/*.spec.ts"],
		coverage: {
			include: [
				"src/entities/character/domain/CharacterService.ts",
				"src/entities/character/domain/CharacterDerivedStatsService.ts",
				"src/entities/character/model/characterRules.ts",
				"src/entities/character/model/characterSchema.ts",
				"src/entities/ancestry/domain/AncestryCatalogService.ts",
				"src/entities/ancestry/domain/AncestryTraitSelectionService.ts",
				"src/entities/character-class/domain/CharacterClassCatalogService.ts",
				"src/entities/background/domain/BackgroundCatalogService.ts",
				"src/entities/camp-activity/domain/CampActivityCatalogService.ts",
				"src/entities/compendium/domain/CompendiumCatalogService.ts",
				"src/entities/compendium/domain/CompendiumSearchService.ts",
				"src/entities/equipment/domain/EquipmentCatalogService.ts",
				"src/entities/equipment/domain/EquipmentLoadoutService.ts",
				"src/entities/equipment/domain/EquipmentWeaponAttackProfileService.ts",
				"src/entities/faction/domain/FactionCatalogService.ts",
				"src/entities/dialogue-choice/domain/DialogueChoiceCatalogService.ts",
				"src/entities/dialogue-tree/domain/DialogueTreeCatalogService.ts",
				"src/entities/npc/domain/NpcCatalogService.ts",
				"src/entities/npc-relationship/infrastructure/DrizzleNpcRelationshipRepository.ts",
				"src/entities/npc-relationship/domain/NpcRelationshipService.ts",
				"src/entities/spell/domain/SpellCatalogService.ts",
				"src/entities/world-tile/domain/WorldTileCatalogService.ts",
				"src/entities/world-state/domain/WorldStateService.ts",
				"src/entities/clock/domain/ClockService.ts",
				"src/shared/dice/domain/DiceService.ts",
				"src/shared/resolution/domain/ResolutionService.ts",
				"src/shared/action-queue/domain/ActionQueueService.ts",
				"src/shared/damage/domain/DamagePipelineService.ts",
				"src/shared/inventory/domain/InventoryCapacityService.ts",
				"src/shared/persistence/domain/SqliteOpfsBootstrapService.ts",
				"src/shared/rpc/infrastructure/BrowserWorkerBridge.ts",
				"src/features/combat-encounter/domain/CombatEncounterService.ts",
				"src/features/combat-encounter/domain/CombatTurnService.ts",
				"src/features/camp-hour/domain/CampHourService.ts",
				"src/features/hexcrawl-map/domain/HexcrawlMovementService.ts",
				"src/features/save-load/domain/SaveLoadService.ts",
				"src/features/save-load/domain/SqliteSaveSnapshotService.ts",
				"src/features/social-encounter/domain/DialogueTraversalService.ts",
				"src/features/social-standing/domain/SocialStandingService.ts",
				"src/features/social-encounter/domain/SocialAppealResolutionService.ts",
				"src/features/social-encounter/domain/SocialEncounterService.ts",
				"src/features/social-retaliation/domain/SocialRetaliationClockService.ts",
				"src/features/spell-cast/domain/SpellCastBuilderService.ts",
				"src/features/character-create/model/characterCreateView.ts",
				"src/features/character-list/model/characterListView.ts",
				"src/features/camp-hour/model/campHourView.ts",
				"src/features/compendium-browser/model/compendiumBrowserView.ts",
				"src/features/hexcrawl-map/model/hexcrawlMapView.ts",
				"src/features/inventory-readonly/model/inventoryReadOnlyView.ts",
				"src/features/save-load/model/saveLoadView.ts",
				"src/features/social-encounter/model/socialDialogueChoiceProfile.ts",
				"src/features/social-encounter/model/socialDialogueTreeView.ts",
				"src/features/social-encounter/model/socialEncounterConsequences.ts",
				"src/features/social-encounter/model/socialEncounterView.ts",
				"src/features/social-relations/model/socialRelationsView.ts",
				"src/features/combat-encounter/model/combatAttackerStatsView.ts",
				"src/features/combat-encounter/model/combatEncounterView.ts",
				"src/features/combat-encounter/model/combatTrainingAttackProfile.ts",
				"src/features/combat-encounter/model/combatTrainingTargetTurn.ts",
				"src/features/spell-cast/model/spellCastView.ts",
				"src/app/model/pwaStatusView.ts",
			],
			exclude: [
				"src/entities/character/testing/**/*.ts",
				"src/entities/character/__tests__/**/*.ts",
			],
			thresholds: {
				lines: 100,
				functions: 100,
				branches: 100,
				statements: 100,
			},
		},
	},
});
