export type JsonValue =
	| string
	| number
	| boolean
	| null
	| readonly JsonValue[]
	| { readonly [key: string]: JsonValue };

export type JsonObject = { readonly [key: string]: JsonValue };

export type RpcCommandType =
	| "INIT_DATABASE"
	| "SAVE_GAME_SNAPSHOT"
	| "LOAD_GAME_SNAPSHOT"
	| "SAVE_CHARACTER"
	| "FIND_CHARACTER"
	| "SAVE_STATUS_EFFECT"
	| "FIND_STATUS_EFFECTS"
	| "DELETE_STATUS_EFFECT"
	| "CAST_SPELL"
	| "SAVE_BASTION"
	| "FIND_BASTION"
	| "SAVE_BASTION_MODULE"
	| "FIND_BASTION_MODULES"
	| "DELETE_BASTION_MODULE"
	| "SAVE_FACTION"
	| "FIND_FACTION"
	| "LIST_FACTIONS"
	| "SAVE_REPUTATION"
	| "FIND_REPUTATION"
	| "LIST_REPUTATIONS"
	| "SAVE_BLOOD_DEBT"
	| "LIST_BLOOD_DEBTS"
	| "SAVE_SOCIAL_LEDGER"
	| "FIND_SOCIAL_LEDGER"
	| "SAVE_CLOCK"
	| "FIND_CLOCK"
	| "LIST_CLOCKS"
	| "DELETE_CLOCK"
	| "SAVE_DIALOGUE_STATE"
	| "FIND_DIALOGUE_STATE"
	| "DELETE_DIALOGUE_STATE"
	| "SAVE_QUEST"
	| "FIND_QUEST"
	| "LIST_QUESTS"
	| "DELETE_QUEST"
	| "SAVE_LORE_ENCOUNTER"
	| "FIND_LORE_ENCOUNTER"
	| "LIST_LORE_ENCOUNTERS_BY_TILE"
	| "LIST_ALL_LORE_ENCOUNTERS"
	| "SAVE_CAMPAIGN_RUMOR"
	| "FIND_CAMPAIGN_RUMOR"
	| "LIST_CAMPAIGN_RUMORS_BY_TILE"
	| "LIST_ALL_CAMPAIGN_RUMORS"
	| "SAVE_COHESION"
	| "FIND_COHESION"
	| "SAVE_SIGNATURE"
	| "FIND_SIGNATURE"
	| "LIST_SIGNATURES"
	| "DELETE_SIGNATURE"
	| "SAVE_TRAP"
	| "FIND_TRAP"
	| "LIST_TRAPS"
	| "DELETE_TRAP"
	| "SAVE_COMPANION"
	| "FIND_COMPANION"
	| "LIST_COMPANIONS"
	| "SAVE_INVESTIGATION"
	| "FIND_INVESTIGATION"
	| "LIST_INVESTIGATIONS_BY_TARGET"
	| "LIST_ACTIVE_INVESTIGATIONS"
	| "SAVE_REGIONAL_DOMAIN"
	| "FIND_REGIONAL_DOMAIN"
	| "LIST_REGIONAL_DOMAINS"
	| "SAVE_CAMP_SESSION"
	| "FIND_CAMP_SESSION"
	| "LIST_CAMP_SESSIONS"
	| "DELETE_CAMP_SESSION"
	| "SAVE_MERCENARY_COMPANY"
	| "FIND_MERCENARY_COMPANY"
	| "LIST_MERCENARY_COMPANIES"
	| "SAVE_MERCENARY_SQUAD"
	| "FIND_MERCENARY_SQUAD"
	| "LIST_MERCENARY_SQUADS_BY_COMPANY"
	| "DISMANTLE_CRAFTED_ITEM"
	| "SCRAP_EQUIPMENT"
	| "LIST_SAVE_SLOTS"
	| "CREATE_SAVE_SLOT"
	| "CLONE_SAVE_SLOT"
	| "DELETE_SAVE_SLOT"
	| "MUTATE_WORLD_STATE"
	| "TICK_CLOCK_MANUAL"
	| "FORCE_SPAWN_ACTOR"
	| "APPLY_LEVEL_UP";

export type RpcBridgeFailureCode =
	| "INVALID_RPC_REQUEST"
	| "RPC_RESPONSE_NOT_QUEUED"
	| "INVALID_RPC_RESPONSE"
	| "RPC_MESSAGE_ID_MISMATCH";

export interface RpcBridgeFailure {
	readonly code: RpcBridgeFailureCode;
	readonly message: string;
	readonly details?: unknown;
}
