import type { ConsumableRecord, EquipmentRecord } from "./equipmentSchema";

export const OFFICIAL_EQUIPMENT = [
	{
		id: "longsword",
		label: "Espada Longa",
		kind: "weapon",
		sourceFile: "docs/system/survival/04-arsenal-e-economia.md",
		slotCost: 2,
		priceCopper: 5000,
		qualityTier: "mundane",
		runeSlots: 1,
		durabilityCurrent: 100,
		durabilityMax: 100,
		mechanicalSummary: "1d8/1d10, Versatil. Item unico de treino.",
	},
	{
		id: "dagger",
		label: "Adaga",
		kind: "weapon",
		sourceFile: "docs/system/survival/04-arsenal-e-economia.md",
		slotCost: 1,
		priceCopper: 2000,
		qualityTier: "mundane",
		runeSlots: 1,
		durabilityCurrent: 100,
		durabilityMax: 100,
		mechanicalSummary: "1d4, Agil, Ocultavel, Arremesso 6m. Item unico.",
	},
	{
		id: "longbow",
		label: "Arco Longo",
		kind: "weapon",
		sourceFile: "docs/system/survival/04-arsenal-e-economia.md",
		slotCost: 2,
		priceCopper: 50000,
		qualityTier: "mundane",
		runeSlots: 1,
		durabilityCurrent: 100,
		durabilityMax: 100,
		mechanicalSummary: "1d8, Alcance 36m, 2 maos. Item unico.",
	},
	{
		id: "leather-armor",
		label: "Armadura de Couro",
		kind: "armor",
		sourceFile: "docs/system/survival/04-arsenal-e-economia.md",
		slotCost: 1,
		priceCopper: 10000,
		qualityTier: "mundane",
		runeSlots: 1,
		durabilityCurrent: 100,
		durabilityMax: 100,
		mechanicalSummary: "+2 CA, Leve, sem penalidades. Item unico.",
	},
	{
		id: "plate-armor",
		label: "Armadura de Placas",
		kind: "armor",
		sourceFile: "docs/system/survival/04-arsenal-e-economia.md",
		slotCost: 2,
		priceCopper: 200000,
		qualityTier: "mundane",
		runeSlots: 1,
		durabilityCurrent: 100,
		durabilityMax: 100,
		mechanicalSummary: "+5 CA, Pesada, Ruidosa, -3m Velocidade. Item unico.",
	},
	{
		id: "round-shield",
		label: "Escudo Redondo",
		kind: "shield",
		sourceFile: "docs/system/survival/04-arsenal-e-economia.md",
		slotCost: 1,
		priceCopper: 10000,
		qualityTier: "mundane",
		runeSlots: 1,
		durabilityCurrent: 100,
		durabilityMax: 100,
		mechanicalSummary: "+1 CA, Leve, permite interagir com a mao. Item unico.",
	},
	{
		id: "magic-ring",
		label: "Anel Magico",
		kind: "weapon",
		sourceFile: "docs/system/survival/04-arsenal-e-economia.md",
		slotCost: 1,
		priceCopper: 10000,
		qualityTier: "mundane",
		runeSlots: 1,
		durabilityCurrent: 100,
		durabilityMax: 100,
		mechanicalSummary: "Um anel de treino.",
	},
] as const satisfies readonly EquipmentRecord[];

export const OFFICIAL_CONSUMABLES = [
	{
		id: "rope-stack",
		label: "Corda",
		kind: "adventuring-item",
		sourceFile: "docs/system/survival/regras-peso-carga.md",
		quantity: 3,
		maxQuantityPerStack: 3,
		slotCostPerStack: 1,
	},
	{
		id: "torch-stack",
		label: "Tocha",
		kind: "adventuring-item",
		sourceFile: "docs/system/survival/regras-peso-carga.md",
		quantity: 3,
		maxQuantityPerStack: 3,
		slotCostPerStack: 1,
	},
	{
		id: "ration-stack",
		label: "Racao",
		kind: "adventuring-item",
		sourceFile: "docs/system/survival/regras-peso-carga.md",
		quantity: 3,
		maxQuantityPerStack: 3,
		slotCostPerStack: 1,
	},
	{
		id: "potion-belt-stack",
		label: "Cinto de Pocoes",
		kind: "potion-belt",
		sourceFile: "docs/system/survival/regras-peso-carga.md",
		quantity: 5,
		maxQuantityPerStack: 5,
		slotCostPerStack: 1,
	},
	{
		id: "first-aid-kit",
		label: "Kit de Primeiros Socorros",
		kind: "adventuring-item",
		sourceFile: "docs/system/survival/00-mecanicas-fundamentais.md",
		quantity: 3,
		maxQuantityPerStack: 3,
		slotCostPerStack: 1,
	},
	{
		id: "gold-coins-stack",
		label: "Moedas de Ouro",
		kind: "currency",
		sourceFile: "docs/system/survival/regras-peso-carga.md",
		quantity: 100,
		maxQuantityPerStack: 100,
		slotCostPerStack: 0,
	},
] as const satisfies readonly ConsumableRecord[];

export const OFFICIAL_EQUIPMENT_IDS = OFFICIAL_EQUIPMENT.map((item) => item.id);

export const OFFICIAL_CONSUMABLE_IDS = OFFICIAL_CONSUMABLES.map(
	(item) => item.id,
);
