// AUTO-GENERATED by scripts/generate_compendium_catalog.mjs
// Do not edit manually. Update docs/system and rerun the generator.
import type { CompendiumEntry } from "./compendiumSchema";

export const GENERATED_COMPENDIUM_ENTRIES = [
	{
		id: "system-combat-03-01-imunidades-resistencias-e-vulnerabilidades",
		title: "03 01 Imunidades Resistencias E Vulnerabilidades",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile:
			"docs/system/combat/03-01-imunidades-resistencias-e-vulnerabilidades.md",
		sourceLine: 7,
		searchText:
			"03 01 Imunidades Resistencias E Vulnerabilidades Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/03-01-imunidades-resistencias-e-vulnerabilidades.md combat system-combat ref-03 ref-01 imunidades resistencias e vulnerabilidades",
		tags: [
			"combat",
			"system-combat",
			"ref-03",
			"ref-01",
			"imunidades",
			"resistencias",
			"e",
			"vulnerabilidades",
		],
	},
	{
		id: "system-combat-03-codex-de-combate-e-condicoes",
		title: "03 Codex De Combate E Condicoes",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/03-codex-de-combate-e-condicoes.md",
		sourceLine: 7,
		searchText:
			"03 Codex De Combate E Condicoes Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/03-codex-de-combate-e-condicoes.md combat system-combat ref-03 codex de combate e condicoes",
		tags: [
			"combat",
			"system-combat",
			"ref-03",
			"codex",
			"de",
			"combate",
			"e",
			"condicoes",
		],
	},
	{
		id: "system-combat-07-01a-tier1-mundo-natural",
		title: "07 01a Tier1 Mundo Natural",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/07-01a-tier1-mundo-natural.md",
		sourceLine: 7,
		searchText:
			"07 01a Tier1 Mundo Natural Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/07-01a-tier1-mundo-natural.md combat system-combat ref-07 ref-01a tier1 mundo natural",
		tags: [
			"combat",
			"system-combat",
			"ref-07",
			"ref-01a",
			"tier1",
			"mundo",
			"natural",
		],
	},
	{
		id: "system-combat-07-01b-tier1-sobrenatural",
		title: "07 01b Tier1 Sobrenatural",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/07-01b-tier1-sobrenatural.md",
		sourceLine: 7,
		searchText:
			"07 01b Tier1 Sobrenatural Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/07-01b-tier1-sobrenatural.md combat system-combat ref-07 ref-01b tier1 sobrenatural",
		tags: [
			"combat",
			"system-combat",
			"ref-07",
			"ref-01b",
			"tier1",
			"sobrenatural",
		],
	},
	{
		id: "system-combat-07-02a-tier2-feras-e-gigantes",
		title: "07 02a Tier2 Feras E Gigantes",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/07-02a-tier2-feras-e-gigantes.md",
		sourceLine: 7,
		searchText:
			"07 02a Tier2 Feras E Gigantes Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/07-02a-tier2-feras-e-gigantes.md combat system-combat ref-07 ref-02a tier2 feras e gigantes",
		tags: [
			"combat",
			"system-combat",
			"ref-07",
			"ref-02a",
			"tier2",
			"feras",
			"e",
			"gigantes",
		],
	},
	{
		id: "system-combat-07-02b-tier2-magia-e-morte",
		title: "07 02b Tier2 Magia E Morte",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/07-02b-tier2-magia-e-morte.md",
		sourceLine: 7,
		searchText:
			"07 02b Tier2 Magia E Morte Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/07-02b-tier2-magia-e-morte.md combat system-combat ref-07 ref-02b tier2 magia e morte",
		tags: [
			"combat",
			"system-combat",
			"ref-07",
			"ref-02b",
			"tier2",
			"magia",
			"e",
			"morte",
		],
	},
	{
		id: "system-combat-07-03a-tier3-lendas-vivas",
		title: "07 03a Tier3 Lendas Vivas",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/07-03a-tier3-lendas-vivas.md",
		sourceLine: 7,
		searchText:
			"07 03a Tier3 Lendas Vivas Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/07-03a-tier3-lendas-vivas.md combat system-combat ref-07 ref-03a tier3 lendas vivas",
		tags: [
			"combat",
			"system-combat",
			"ref-07",
			"ref-03a",
			"tier3",
			"lendas",
			"vivas",
		],
	},
	{
		id: "system-combat-07-03b-tier3-horrores-etericos",
		title: "07 03b Tier3 Horrores Etericos",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/07-03b-tier3-horrores-etericos.md",
		sourceLine: 7,
		searchText:
			"07 03b Tier3 Horrores Etericos Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/07-03b-tier3-horrores-etericos.md combat system-combat ref-07 ref-03b tier3 horrores etericos",
		tags: [
			"combat",
			"system-combat",
			"ref-07",
			"ref-03b",
			"tier3",
			"horrores",
			"etericos",
		],
	},
	{
		id: "system-combat-07-04a-tier4-deuses-e-titans",
		title: "07 04a Tier4 Deuses E Titans",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/07-04a-tier4-deuses-e-titans.md",
		sourceLine: 7,
		searchText:
			"07 04a Tier4 Deuses E Titans Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/07-04a-tier4-deuses-e-titans.md combat system-combat ref-07 ref-04a tier4 deuses e titans",
		tags: [
			"combat",
			"system-combat",
			"ref-07",
			"ref-04a",
			"tier4",
			"deuses",
			"e",
			"titans",
		],
	},
	{
		id: "system-combat-13-guia-de-criacao-de-monstros",
		title: "13 Guia De Criacao De Monstros",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/13-guia-de-criacao-de-monstros.md",
		sourceLine: 7,
		searchText:
			"13 Guia De Criacao De Monstros Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/13-guia-de-criacao-de-monstros.md combat system-combat ref-13 guia de criacao monstros",
		tags: [
			"combat",
			"system-combat",
			"ref-13",
			"guia",
			"de",
			"criacao",
			"monstros",
		],
	},
	{
		id: "system-combat-14-compendio-de-habilidades-de-monstros",
		title: "14 Compendio De Habilidades De Monstros",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/14-compendio-de-habilidades-de-monstros.md",
		sourceLine: 7,
		searchText:
			"14 Compendio De Habilidades De Monstros Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/14-compendio-de-habilidades-de-monstros.md combat system-combat ref-14 compendio de habilidades monstros",
		tags: [
			"combat",
			"system-combat",
			"ref-14",
			"compendio",
			"de",
			"habilidades",
			"monstros",
		],
	},
	{
		id: "system-combat-15-compendio-de-habilidades-de-monstros-tier2",
		title: "15 Compendio De Habilidades De Monstros Tier2",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile:
			"docs/system/combat/15-compendio-de-habilidades-de-monstros-tier2.md",
		sourceLine: 7,
		searchText:
			"15 Compendio De Habilidades De Monstros Tier2 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/15-compendio-de-habilidades-de-monstros-tier2.md combat system-combat ref-15 compendio de habilidades monstros",
		tags: [
			"combat",
			"system-combat",
			"ref-15",
			"compendio",
			"de",
			"habilidades",
			"monstros",
		],
	},
	{
		id: "system-combat-16-compendio-de-habilidades-de-monstros-tier3",
		title: "16 Compendio De Habilidades De Monstros Tier3",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile:
			"docs/system/combat/16-compendio-de-habilidades-de-monstros-tier3.md",
		sourceLine: 7,
		searchText:
			"16 Compendio De Habilidades De Monstros Tier3 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/16-compendio-de-habilidades-de-monstros-tier3.md combat system-combat ref-16 compendio de habilidades monstros",
		tags: [
			"combat",
			"system-combat",
			"ref-16",
			"compendio",
			"de",
			"habilidades",
			"monstros",
		],
	},
	{
		id: "system-combat-17-compendio-de-habilidades-de-monstros-tier4",
		title: "17 Compendio De Habilidades De Monstros Tier4",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile:
			"docs/system/combat/17-compendio-de-habilidades-de-monstros-tier4.md",
		sourceLine: 7,
		searchText:
			"17 Compendio De Habilidades De Monstros Tier4 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/17-compendio-de-habilidades-de-monstros-tier4.md combat system-combat ref-17 compendio de habilidades monstros",
		tags: [
			"combat",
			"system-combat",
			"ref-17",
			"compendio",
			"de",
			"habilidades",
			"monstros",
		],
	},
	{
		id: "system-combat-18-tratado-de-dano",
		title: "18 Tratado De Dano",
		category: "system-combat",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/combat/18-tratado-de-dano.md",
		sourceLine: 7,
		searchText:
			"18 Tratado De Dano Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/combat/18-tratado-de-dano.md combat system-combat ref-18 tratado de dano",
		tags: ["combat", "system-combat", "ref-18", "tratado", "de", "dano"],
	},
	{
		id: "system-magic-12-00-codex-de-magia",
		title: "12 00 Codex De Magia",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-00-codex-de-magia.md",
		sourceLine: 7,
		searchText:
			"12 00 Codex De Magia Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-00-codex-de-magia.md magic system-magic ref-12 ref-00 codex de magia",
		tags: ["magic", "system-magic", "ref-12", "ref-00", "codex", "de", "magia"],
	},
	{
		id: "system-magic-12-01-grimorio-arcano",
		title: "12 01 Grimorio Arcano",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-01-grimorio-arcano.md",
		sourceLine: 7,
		searchText:
			"12 01 Grimorio Arcano Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-01-grimorio-arcano.md magic system-magic ref-12 ref-01 grimorio arcano",
		tags: ["magic", "system-magic", "ref-12", "ref-01", "grimorio", "arcano"],
	},
	{
		id: "system-magic-12-02-grimorio-circulo-0",
		title: "12 02 Grimorio Circulo 0",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-02-grimorio-circulo-0.md",
		sourceLine: 7,
		searchText:
			"12 02 Grimorio Circulo 0 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-02-grimorio-circulo-0.md magic system-magic ref-12 ref-02 grimorio circulo ref-0",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-02",
			"grimorio",
			"circulo",
			"ref-0",
		],
	},
	{
		id: "system-magic-12-03-grimorio-circulo-1",
		title: "12 03 Grimorio Circulo 1",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-03-grimorio-circulo-1.md",
		sourceLine: 7,
		searchText:
			"12 03 Grimorio Circulo 1 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-03-grimorio-circulo-1.md magic system-magic ref-12 ref-03 grimorio circulo ref-1",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-03",
			"grimorio",
			"circulo",
			"ref-1",
		],
	},
	{
		id: "system-magic-12-04-grimorio-circulo-2",
		title: "12 04 Grimorio Circulo 2",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-04-grimorio-circulo-2.md",
		sourceLine: 7,
		searchText:
			"12 04 Grimorio Circulo 2 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-04-grimorio-circulo-2.md magic system-magic ref-12 ref-04 grimorio circulo ref-2",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-04",
			"grimorio",
			"circulo",
			"ref-2",
		],
	},
	{
		id: "system-magic-12-05-grimorio-circulo-3",
		title: "12 05 Grimorio Circulo 3",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-05-grimorio-circulo-3.md",
		sourceLine: 7,
		searchText:
			"12 05 Grimorio Circulo 3 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-05-grimorio-circulo-3.md magic system-magic ref-12 ref-05 grimorio circulo ref-3",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-05",
			"grimorio",
			"circulo",
			"ref-3",
		],
	},
	{
		id: "system-magic-12-06-grimorio-circulo-4",
		title: "12 06 Grimorio Circulo 4",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-06-grimorio-circulo-4.md",
		sourceLine: 7,
		searchText:
			"12 06 Grimorio Circulo 4 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-06-grimorio-circulo-4.md magic system-magic ref-12 ref-06 grimorio circulo ref-4",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-06",
			"grimorio",
			"circulo",
			"ref-4",
		],
	},
	{
		id: "system-magic-12-07-grimorio-circulo-5",
		title: "12 07 Grimorio Circulo 5",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-07-grimorio-circulo-5.md",
		sourceLine: 7,
		searchText:
			"12 07 Grimorio Circulo 5 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-07-grimorio-circulo-5.md magic system-magic ref-12 ref-07 grimorio circulo ref-5",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-07",
			"grimorio",
			"circulo",
			"ref-5",
		],
	},
	{
		id: "system-magic-12-08-grimorio-circulo-6",
		title: "12 08 Grimorio Circulo 6",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-08-grimorio-circulo-6.md",
		sourceLine: 7,
		searchText:
			"12 08 Grimorio Circulo 6 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-08-grimorio-circulo-6.md magic system-magic ref-12 ref-08 grimorio circulo ref-6",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-08",
			"grimorio",
			"circulo",
			"ref-6",
		],
	},
	{
		id: "system-magic-12-09-grimorio-circulo-7",
		title: "12 09 Grimorio Circulo 7",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-09-grimorio-circulo-7.md",
		sourceLine: 7,
		searchText:
			"12 09 Grimorio Circulo 7 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-09-grimorio-circulo-7.md magic system-magic ref-12 ref-09 grimorio circulo ref-7",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-09",
			"grimorio",
			"circulo",
			"ref-7",
		],
	},
	{
		id: "system-magic-12-10-grimorio-circulo-8",
		title: "12 10 Grimorio Circulo 8",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-10-grimorio-circulo-8.md",
		sourceLine: 7,
		searchText:
			"12 10 Grimorio Circulo 8 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-10-grimorio-circulo-8.md magic system-magic ref-12 ref-10 grimorio circulo ref-8",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-10",
			"grimorio",
			"circulo",
			"ref-8",
		],
	},
	{
		id: "system-magic-12-11-grimorio-circulo-9",
		title: "12 11 Grimorio Circulo 9",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-11-grimorio-circulo-9.md",
		sourceLine: 7,
		searchText:
			"12 11 Grimorio Circulo 9 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-11-grimorio-circulo-9.md magic system-magic ref-12 ref-11 grimorio circulo ref-9",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-11",
			"grimorio",
			"circulo",
			"ref-9",
		],
	},
	{
		id: "system-magic-12-12-grimorio-circulo-10",
		title: "12 12 Grimorio Circulo 10",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-12-grimorio-circulo-10.md",
		sourceLine: 7,
		searchText:
			"12 12 Grimorio Circulo 10 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-12-grimorio-circulo-10.md magic system-magic ref-12 grimorio circulo ref-10",
		tags: ["magic", "system-magic", "ref-12", "grimorio", "circulo", "ref-10"],
	},
	{
		id: "system-magic-12-13-codex-expandido-magia-hibrida",
		title: "12 13 Codex Expandido Magia Hibrida",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-13-codex-expandido-magia-hibrida.md",
		sourceLine: 7,
		searchText:
			"12 13 Codex Expandido Magia Hibrida Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-13-codex-expandido-magia-hibrida.md magic system-magic ref-12 ref-13 codex expandido magia hibrida",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"ref-13",
			"codex",
			"expandido",
			"magia",
			"hibrida",
		],
	},
	{
		id: "system-magic-12-metamagias-as-40-quebras",
		title: "12 Metamagias As 40 Quebras",
		category: "system-magic",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/magic/12-metamagias-as-40-quebras.md",
		sourceLine: 7,
		searchText:
			"12 Metamagias As 40 Quebras Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/magic/12-metamagias-as-40-quebras.md magic system-magic ref-12 metamagias as ref-40 quebras",
		tags: [
			"magic",
			"system-magic",
			"ref-12",
			"metamagias",
			"as",
			"ref-40",
			"quebras",
		],
	},
	{
		id: "system-survival-00-mecanicas-fundamentais",
		title: "00 - Mecânicas Fundamentais",
		category: "system-survival",
		summary:
			"Para cada ponto em um Eixo (Físico, Mental, Social), você escolhe 1 Tática de Sinergia daquela Matriz para aprender. Estas táticas são usadas exclusivamente no Ciclo de Sinergia para criar combos táticos com seus aliados.",
		sourceFile: "docs/system/survival/00-mecanicas-fundamentais.md",
		sourceLine: 7,
		searchText:
			"00 - Mecânicas Fundamentais Para cada ponto em um Eixo (Físico, Mental, Social), você escolhe 1 Tática de Sinergia daquela Matriz para aprender. Estas táticas são usadas exclusivamente no Ciclo de Sinergia para criar combos táticos com seus aliados. docs/system/survival/00-mecanicas-fundamentais.md survival system-survival ref-00 mecanicas fundamentais",
		tags: [
			"survival",
			"system-survival",
			"ref-00",
			"mecanicas",
			"fundamentais",
		],
	},
	{
		id: "system-survival-01-00-regras-gerais",
		title: "01 00 Regras Gerais",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/01-00-regras-gerais.md",
		sourceLine: 8,
		searchText:
			"01 00 Regras Gerais Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/01-00-regras-gerais.md survival system-survival ref-01 ref-00 regras gerais",
		tags: [
			"survival",
			"system-survival",
			"ref-01",
			"ref-00",
			"regras",
			"gerais",
		],
	},
	{
		id: "system-survival-01-01-humanos",
		title: "01 - Humanos (Os Sobreviventes de Morden)",
		category: "system-survival",
		summary:
			"Escolha +1 em um Eixo (Físico, Mental ou Social) OU +1 em uma Aplicação (Interação, Conflito ou Resistência).",
		sourceFile: "docs/system/survival/01-01-humanos.md",
		sourceLine: 7,
		searchText:
			"01 - Humanos (Os Sobreviventes de Morden) Escolha +1 em um Eixo (Físico, Mental ou Social) OU +1 em uma Aplicação (Interação, Conflito ou Resistência). docs/system/survival/01-01-humanos.md survival system-survival ref-01 humanos",
		tags: ["survival", "system-survival", "ref-01", "humanos"],
	},
	{
		id: "system-survival-01-02-elfos",
		title: "02 - Elfos (Os Tecelões das Eras)",
		category: "system-survival",
		summary: "Escolha +1 no Eixo Mental OU +1 na Aplicação Interação.",
		sourceFile: "docs/system/survival/01-02-elfos.md",
		sourceLine: 7,
		searchText:
			"02 - Elfos (Os Tecelões das Eras) Escolha +1 no Eixo Mental OU +1 na Aplicação Interação. docs/system/survival/01-02-elfos.md survival system-survival ref-01 ref-02 elfos",
		tags: ["survival", "system-survival", "ref-01", "ref-02", "elfos"],
	},
	{
		id: "system-survival-01-03-anoes",
		title: "03 - Anões (Os Guardiões da Raiz)",
		category: "system-survival",
		summary: "Escolha +1 no Eixo Físico OU +1 na Aplicação Resistência.",
		sourceFile: "docs/system/survival/01-03-anoes.md",
		sourceLine: 7,
		searchText:
			"03 - Anões (Os Guardiões da Raiz) Escolha +1 no Eixo Físico OU +1 na Aplicação Resistência. docs/system/survival/01-03-anoes.md survival system-survival ref-01 ref-03 anoes",
		tags: ["survival", "system-survival", "ref-01", "ref-03", "anoes"],
	},
	{
		id: "system-survival-01-04-drakari",
		title: "04 - Drakari (Os Senhores do Metal Vivo)",
		category: "system-survival",
		summary: "Escolha +1 no Eixo Físico OU +1 na Aplicação Conflito.",
		sourceFile: "docs/system/survival/01-04-drakari.md",
		sourceLine: 7,
		searchText:
			"04 - Drakari (Os Senhores do Metal Vivo) Escolha +1 no Eixo Físico OU +1 na Aplicação Conflito. docs/system/survival/01-04-drakari.md survival system-survival ref-01 ref-04 drakari",
		tags: ["survival", "system-survival", "ref-01", "ref-04", "drakari"],
	},
	{
		id: "system-survival-01-05-umbrais",
		title: "05 - Umbrais (Os Andarilhos do Vazio)",
		category: "system-survival",
		summary: "Escolha +1 no Eixo Mental OU +1 na Aplicação Interação.",
		sourceFile: "docs/system/survival/01-05-umbrais.md",
		sourceLine: 7,
		searchText:
			"05 - Umbrais (Os Andarilhos do Vazio) Escolha +1 no Eixo Mental OU +1 na Aplicação Interação. docs/system/survival/01-05-umbrais.md survival system-survival ref-01 ref-05 umbrais",
		tags: ["survival", "system-survival", "ref-01", "ref-05", "umbrais"],
	},
	{
		id: "system-survival-01-06-feras",
		title: "06 - Feras (Os Predadores do Éter)",
		category: "system-survival",
		summary: "Escolha +1 no Eixo Físico OU +1 na Aplicação Conflito.",
		sourceFile: "docs/system/survival/01-06-feras.md",
		sourceLine: 7,
		searchText:
			"06 - Feras (Os Predadores do Éter) Escolha +1 no Eixo Físico OU +1 na Aplicação Conflito. docs/system/survival/01-06-feras.md survival system-survival ref-01 ref-06 feras",
		tags: ["survival", "system-survival", "ref-01", "ref-06", "feras"],
	},
	{
		id: "system-survival-01-ancestralidades",
		title: "01 Ancestralidades",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/01-ancestralidades.md",
		sourceLine: 8,
		searchText:
			"01 Ancestralidades Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/01-ancestralidades.md survival system-survival ref-01 ancestralidades",
		tags: ["survival", "system-survival", "ref-01", "ancestralidades"],
	},
	{
		id: "system-survival-02a-matriz-fisica",
		title: "02a Matriz Fisica",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/02a-matriz-fisica.md",
		sourceLine: 8,
		searchText:
			"02a Matriz Fisica Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/02a-matriz-fisica.md survival system-survival ref-02a matriz fisica",
		tags: ["survival", "system-survival", "ref-02a", "matriz", "fisica"],
	},
	{
		id: "system-survival-02b-matriz-mental",
		title: "02b Matriz Mental",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/02b-matriz-mental.md",
		sourceLine: 8,
		searchText:
			"02b Matriz Mental Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/02b-matriz-mental.md survival system-survival ref-02b matriz mental",
		tags: ["survival", "system-survival", "ref-02b", "matriz", "mental"],
	},
	{
		id: "system-survival-02c-matriz-social",
		title: "02c Matriz Social",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/02c-matriz-social.md",
		sourceLine: 8,
		searchText:
			"02c Matriz Social Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/02c-matriz-social.md survival system-survival ref-02c matriz social",
		tags: ["survival", "system-survival", "ref-02c", "matriz", "social"],
	},
	{
		id: "system-survival-04-arsenal-e-economia",
		title: "04 - Arsenal e Economia (Edição Definitiva)",
		category: "system-survival",
		summary:
			"[Físico + Resistência] + 6 Slots. Peso Excedente: Se passar do limite, ganha condição Lento (-3m velocidade). Sobrecarga: Se passar do limite + 5, fica Imobilizado.",
		sourceFile: "docs/system/survival/04-arsenal-e-economia.md",
		sourceLine: 7,
		searchText:
			"04 - Arsenal e Economia (Edição Definitiva) [Físico + Resistência] + 6 Slots. Peso Excedente: Se passar do limite, ganha condição Lento (-3m velocidade). Sobrecarga: Se passar do limite + 5, fica Imobilizado. docs/system/survival/04-arsenal-e-economia.md survival system-survival ref-04 arsenal e economia",
		tags: ["survival", "system-survival", "ref-04", "arsenal", "e", "economia"],
	},
	{
		id: "system-survival-05-00-regras-de-classe",
		title: "05 00 Regras De Classe",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/05-00-regras-de-classe.md",
		sourceLine: 8,
		searchText:
			"05 00 Regras De Classe Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/05-00-regras-de-classe.md survival system-survival ref-05 ref-00 regras de classe",
		tags: [
			"survival",
			"system-survival",
			"ref-05",
			"ref-00",
			"regras",
			"de",
			"classe",
		],
	},
	{
		id: "system-survival-05-01-vanguarda",
		title: "05.01 - Vanguarda (A Legião de Ferro)",
		category: "system-survival",
		summary:
			"Eixos: Físico/Resistência e Conflito. Vitalidade: HP Base 10 + Físico + Resistência. (Classe mais robusta). Equipamento: Treinamento em todas as Armas, Armaduras e Escudos.",
		sourceFile: "docs/system/survival/05-01-vanguarda.md",
		sourceLine: 7,
		searchText:
			"05.01 - Vanguarda (A Legião de Ferro) Eixos: Físico/Resistência e Conflito. Vitalidade: HP Base 10 + Físico + Resistência. (Classe mais robusta). Equipamento: Treinamento em todas as Armas, Armaduras e Escudos. docs/system/survival/05-01-vanguarda.md survival system-survival ref-05 ref-01 vanguarda",
		tags: ["survival", "system-survival", "ref-05", "ref-01", "vanguarda"],
	},
	{
		id: "system-survival-05-02-tecelao",
		title: "05.02 - Tecelão de Sombras (O Arcano)",
		category: "system-survival",
		summary:
			"Eixos: Mental/Conflito e Interação. Vitalidade: HP Base 6 + Físico + Resistência. Energia: +5 Energia Etérica (EE) adicional. Equipamento: Armas Simples, Sem Armadura (metal interfere no fluxo).",
		sourceFile: "docs/system/survival/05-02-tecelao.md",
		sourceLine: 7,
		searchText:
			"05.02 - Tecelão de Sombras (O Arcano) Eixos: Mental/Conflito e Interação. Vitalidade: HP Base 6 + Físico + Resistência. Energia: +5 Energia Etérica (EE) adicional. Equipamento: Armas Simples, Sem Armadura (metal interfere no fluxo). docs/system/survival/05-02-tecelao.md survival system-survival ref-05 ref-02 tecelao",
		tags: ["survival", "system-survival", "ref-05", "ref-02", "tecelao"],
	},
	{
		id: "system-survival-05-03-emissario",
		title: "05.03 - Emissário (A Voz do Destino)",
		category: "system-survival",
		summary:
			"Eixos: Social/Interação e Conflito. Vitalidade: HP Base 8 + Físico + Resistência. Equipamento: Armas Leves, Marciais e Armaduras até Médias.",
		sourceFile: "docs/system/survival/05-03-emissario.md",
		sourceLine: 7,
		searchText:
			"05.03 - Emissário (A Voz do Destino) Eixos: Social/Interação e Conflito. Vitalidade: HP Base 8 + Físico + Resistência. Equipamento: Armas Leves, Marciais e Armaduras até Médias. docs/system/survival/05-03-emissario.md survival system-survival ref-05 ref-03 emissario",
		tags: ["survival", "system-survival", "ref-05", "ref-03", "emissario"],
	},
	{
		id: "system-survival-05-04-cacador",
		title: "05.04 - Caçador (O Guardião Selvagem)",
		category: "system-survival",
		summary:
			"Eixos: Híbrido (Escolha 2 primários no nível 1). Vitalidade: HP Base 8 + Físico + Resistência. Classe com mais estamina. Equipamento: Armas de Distância, Leves e Armaduras até Médias.",
		sourceFile: "docs/system/survival/05-04-cacador.md",
		sourceLine: 7,
		searchText:
			"05.04 - Caçador (O Guardião Selvagem) Eixos: Híbrido (Escolha 2 primários no nível 1). Vitalidade: HP Base 8 + Físico + Resistência. Classe com mais estamina. Equipamento: Armas de Distância, Leves e Armaduras até Médias. docs/system/survival/05-04-cacador.md survival system-survival ref-05 ref-04 cacador",
		tags: ["survival", "system-survival", "ref-05", "ref-04", "cacador"],
	},
	{
		id: "system-survival-06-npcs-e-aliados",
		title: "06 Npcs E Aliados",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/06-npcs-e-aliados.md",
		sourceLine: 8,
		searchText:
			"06 Npcs E Aliados Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/06-npcs-e-aliados.md survival system-survival ref-06 npcs e aliados",
		tags: ["survival", "system-survival", "ref-06", "npcs", "e", "aliados"],
	},
	{
		id: "system-survival-08-guia-do-mestre",
		title: "08 Guia Do Mestre",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/08-guia-do-mestre.md",
		sourceLine: 8,
		searchText:
			"08 Guia Do Mestre Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/08-guia-do-mestre.md survival system-survival ref-08 guia do mestre",
		tags: ["survival", "system-survival", "ref-08", "guia", "do", "mestre"],
	},
	{
		id: "system-survival-09-guia-do-artifice-e-criacao",
		title: "09 - Guia do Artífice (Sistema de Criação)",
		category: "system-survival",
		summary:
			"1. Receita: Conhecimento técnico do item. 2. Materiais: Recursos e reagentes necessários. 3. Trabalho: Tempo investido e ferramentas adequadas.",
		sourceFile: "docs/system/survival/09-guia-do-artifice-e-criacao.md",
		sourceLine: 7,
		searchText:
			"09 - Guia do Artífice (Sistema de Criação) 1. Receita: Conhecimento técnico do item. 2. Materiais: Recursos e reagentes necessários. 3. Trabalho: Tempo investido e ferramentas adequadas. docs/system/survival/09-guia-do-artifice-e-criacao.md survival system-survival ref-09 guia do artifice e criacao",
		tags: [
			"survival",
			"system-survival",
			"ref-09",
			"guia",
			"do",
			"artifice",
			"e",
			"criacao",
		],
	},
	{
		id: "system-survival-10-antecedentes-e-origens",
		title: "10 Antecedentes E Origens",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/10-antecedentes-e-origens.md",
		sourceLine: 8,
		searchText:
			"10 Antecedentes E Origens Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/10-antecedentes-e-origens.md survival system-survival ref-10 antecedentes e origens",
		tags: [
			"survival",
			"system-survival",
			"ref-10",
			"antecedentes",
			"e",
			"origens",
		],
	},
	{
		id: "system-survival-19-codex-de-enfermidades",
		title: "19 Codex De Enfermidades",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/19-codex-de-enfermidades.md",
		sourceLine: 8,
		searchText:
			"19 Codex De Enfermidades Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/19-codex-de-enfermidades.md survival system-survival ref-19 codex de enfermidades",
		tags: [
			"survival",
			"system-survival",
			"ref-19",
			"codex",
			"de",
			"enfermidades",
		],
	},
	{
		id: "system-survival-20-codex-de-toxinas",
		title: "20 Codex De Toxinas",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/20-codex-de-toxinas.md",
		sourceLine: 8,
		searchText:
			"20 Codex De Toxinas Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/20-codex-de-toxinas.md survival system-survival ref-20 codex de toxinas",
		tags: ["survival", "system-survival", "ref-20", "codex", "de", "toxinas"],
	},
	{
		id: "system-survival-21-mecanicas-de-fama-e-influencia",
		title: "21 Mecanicas De Fama E Influencia",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/21-mecanicas-de-fama-e-influencia.md",
		sourceLine: 8,
		searchText:
			"21 Mecanicas De Fama E Influencia Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/21-mecanicas-de-fama-e-influencia.md survival system-survival ref-21 mecanicas de fama e influencia",
		tags: [
			"survival",
			"system-survival",
			"ref-21",
			"mecanicas",
			"de",
			"fama",
			"e",
			"influencia",
		],
	},
	{
		id: "system-survival-22-codex-de-exploracao-e-downtime",
		title: "22 Codex De Exploracao E Downtime",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/22-codex-de-exploracao-e-downtime.md",
		sourceLine: 8,
		searchText:
			"22 Codex De Exploracao E Downtime Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/22-codex-de-exploracao-e-downtime.md survival system-survival ref-22 codex de exploracao e downtime",
		tags: [
			"survival",
			"system-survival",
			"ref-22",
			"codex",
			"de",
			"exploracao",
			"e",
			"downtime",
		],
	},
	{
		id: "system-survival-23-codex-de-armadilhas",
		title: "23 Codex De Armadilhas",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/23-codex-de-armadilhas.md",
		sourceLine: 8,
		searchText:
			"23 Codex De Armadilhas Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/23-codex-de-armadilhas.md survival system-survival ref-23 codex de armadilhas",
		tags: [
			"survival",
			"system-survival",
			"ref-23",
			"codex",
			"de",
			"armadilhas",
		],
	},
	{
		id: "system-survival-23a-codex-armadilhas-tier1",
		title: "23a Codex Armadilhas Tier1",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/23a-codex-armadilhas-tier1.md",
		sourceLine: 8,
		searchText:
			"23a Codex Armadilhas Tier1 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/23a-codex-armadilhas-tier1.md survival system-survival ref-23a codex armadilhas tier1",
		tags: [
			"survival",
			"system-survival",
			"ref-23a",
			"codex",
			"armadilhas",
			"tier1",
		],
	},
	{
		id: "system-survival-23b-codex-armadilhas-tier2",
		title: "23b Codex Armadilhas Tier2",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/23b-codex-armadilhas-tier2.md",
		sourceLine: 8,
		searchText:
			"23b Codex Armadilhas Tier2 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/23b-codex-armadilhas-tier2.md survival system-survival ref-23b codex armadilhas tier2",
		tags: [
			"survival",
			"system-survival",
			"ref-23b",
			"codex",
			"armadilhas",
			"tier2",
		],
	},
	{
		id: "system-survival-23c-codex-armadilhas-tier3",
		title: "23c Codex Armadilhas Tier3",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/23c-codex-armadilhas-tier3.md",
		sourceLine: 8,
		searchText:
			"23c Codex Armadilhas Tier3 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/23c-codex-armadilhas-tier3.md survival system-survival ref-23c codex armadilhas tier3",
		tags: [
			"survival",
			"system-survival",
			"ref-23c",
			"codex",
			"armadilhas",
			"tier3",
		],
	},
	{
		id: "system-survival-23d-codex-armadilhas-tier4",
		title: "23d Codex Armadilhas Tier4",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/23d-codex-armadilhas-tier4.md",
		sourceLine: 8,
		searchText:
			"23d Codex Armadilhas Tier4 Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/23d-codex-armadilhas-tier4.md survival system-survival ref-23d codex armadilhas tier4",
		tags: [
			"survival",
			"system-survival",
			"ref-23d",
			"codex",
			"armadilhas",
			"tier4",
		],
	},
	{
		id: "system-survival-24-codex-companheiros-animais",
		title: "24 Codex Companheiros Animais",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/24-codex-companheiros-animais.md",
		sourceLine: 8,
		searchText:
			"24 Codex Companheiros Animais Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/24-codex-companheiros-animais.md survival system-survival ref-24 codex companheiros animais",
		tags: [
			"survival",
			"system-survival",
			"ref-24",
			"codex",
			"companheiros",
			"animais",
		],
	},
	{
		id: "system-survival-25-codex-familiar-mistico",
		title: "25 Codex Familiar Mistico",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/25-codex-familiar-mistico.md",
		sourceLine: 8,
		searchText:
			"25 Codex Familiar Mistico Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/25-codex-familiar-mistico.md survival system-survival ref-25 codex familiar mistico",
		tags: [
			"survival",
			"system-survival",
			"ref-25",
			"codex",
			"familiar",
			"mistico",
		],
	},
	{
		id: "system-survival-26-codex-sinergia-forja-tatica",
		title: "26 Codex Sinergia Forja Tatica",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/26-codex-sinergia-forja-tatica.md",
		sourceLine: 8,
		searchText:
			"26 Codex Sinergia Forja Tatica Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/26-codex-sinergia-forja-tatica.md survival system-survival ref-26 codex sinergia forja tatica",
		tags: [
			"survival",
			"system-survival",
			"ref-26",
			"codex",
			"sinergia",
			"forja",
			"tatica",
		],
	},
	{
		id: "system-survival-27-codex-influencia-dominio-regional",
		title: "27 Codex Influencia Dominio Regional",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/27-codex-influencia-dominio-regional.md",
		sourceLine: 8,
		searchText:
			"27 Codex Influencia Dominio Regional Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/27-codex-influencia-dominio-regional.md survival system-survival ref-27 codex influencia dominio regional",
		tags: [
			"survival",
			"system-survival",
			"ref-27",
			"codex",
			"influencia",
			"dominio",
			"regional",
		],
	},
	{
		id: "system-survival-27-regras-doencas-venenos",
		title: "27 Regras Doencas Venenos",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/27-regras-doencas-venenos.md",
		sourceLine: 8,
		searchText:
			"27 Regras Doencas Venenos Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/27-regras-doencas-venenos.md survival system-survival ref-27 regras doencas venenos",
		tags: [
			"survival",
			"system-survival",
			"ref-27",
			"regras",
			"doencas",
			"venenos",
		],
	},
	{
		id: "system-survival-28-codex-acampamento-descanso-ativo",
		title: "28 Codex Acampamento Descanso Ativo",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/28-codex-acampamento-descanso-ativo.md",
		sourceLine: 8,
		searchText:
			"28 Codex Acampamento Descanso Ativo Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/28-codex-acampamento-descanso-ativo.md survival system-survival ref-28 codex acampamento descanso ativo",
		tags: [
			"survival",
			"system-survival",
			"ref-28",
			"codex",
			"acampamento",
			"descanso",
			"ativo",
		],
	},
	{
		id: "system-survival-29-codex-companhia-mercenaria",
		title: "29 Codex Companhia Mercenaria",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/29-codex-companhia-mercenaria.md",
		sourceLine: 8,
		searchText:
			"29 Codex Companhia Mercenaria Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/29-codex-companhia-mercenaria.md survival system-survival ref-29 codex companhia mercenaria",
		tags: [
			"survival",
			"system-survival",
			"ref-29",
			"codex",
			"companhia",
			"mercenaria",
		],
	},
	{
		id: "system-survival-30-codex-do-bastiao",
		title: "30 Codex Do Bastiao",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/30-codex-do-bastiao.md",
		sourceLine: 8,
		searchText:
			"30 Codex Do Bastiao Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/30-codex-do-bastiao.md survival system-survival ref-30 codex do bastiao",
		tags: ["survival", "system-survival", "ref-30", "codex", "do", "bastiao"],
	},
	{
		id: "system-survival-31-codex-teia-infamia-patrocinio",
		title: "31 Codex Teia Infamia Patrocinio",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/31-codex-teia-infamia-patrocinio.md",
		sourceLine: 8,
		searchText:
			"31 Codex Teia Infamia Patrocinio Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/31-codex-teia-infamia-patrocinio.md survival system-survival ref-31 codex teia infamia patrocinio",
		tags: [
			"survival",
			"system-survival",
			"ref-31",
			"codex",
			"teia",
			"infamia",
			"patrocinio",
		],
	},
	{
		id: "system-survival-a-arte-da-tecelagem-aquisi-o-de-metamagias",
		title: "A Arte Da Tecelagem Aquisi O De Metamagias",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile:
			"docs/system/survival/a-arte-da-tecelagem-aquisi-o-de-metamagias.md",
		sourceLine: 8,
		searchText:
			"A Arte Da Tecelagem Aquisi O De Metamagias Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/a-arte-da-tecelagem-aquisi-o-de-metamagias.md survival system-survival a arte da tecelagem aquisi o",
		tags: [
			"survival",
			"system-survival",
			"a",
			"arte",
			"da",
			"tecelagem",
			"aquisi",
			"o",
		],
	},
	{
		id: "system-survival-c-dex-de-hexcrawl-e-explora-o",
		title: "C Dex De Hexcrawl E Explora O",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/c-dex-de-hexcrawl-e-explora-o.md",
		sourceLine: 8,
		searchText:
			"C Dex De Hexcrawl E Explora O Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/c-dex-de-hexcrawl-e-explora-o.md survival system-survival c dex de hexcrawl e explora",
		tags: [
			"survival",
			"system-survival",
			"c",
			"dex",
			"de",
			"hexcrawl",
			"e",
			"explora",
		],
	},
	{
		id: "system-survival-c-dex-de-investiga-o-e-descoberta",
		title: "C Dex De Investiga O E Descoberta",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/c-dex-de-investiga-o-e-descoberta.md",
		sourceLine: 8,
		searchText:
			"C Dex De Investiga O E Descoberta Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/c-dex-de-investiga-o-e-descoberta.md survival system-survival c dex de investiga o e",
		tags: [
			"survival",
			"system-survival",
			"c",
			"dex",
			"de",
			"investiga",
			"o",
			"e",
		],
	},
	{
		id: "system-survival-c-dice-de-espionagem",
		title: "C Dice De Espionagem",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/c-dice-de-espionagem.md",
		sourceLine: 8,
		searchText:
			"C Dice De Espionagem Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/c-dice-de-espionagem.md survival system-survival c dice de espionagem",
		tags: ["survival", "system-survival", "c", "dice", "de", "espionagem"],
	},
	{
		id: "system-survival-capitulo-xx-contramagia-e-anulacao",
		title: "Capitulo Xx Contramagia E Anulacao",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/capitulo-xx-contramagia-e-anulacao.md",
		sourceLine: 8,
		searchText:
			"Capitulo Xx Contramagia E Anulacao Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/capitulo-xx-contramagia-e-anulacao.md survival system-survival capitulo xx contramagia e anulacao",
		tags: [
			"survival",
			"system-survival",
			"capitulo",
			"xx",
			"contramagia",
			"e",
			"anulacao",
		],
	},
	{
		id: "system-survival-capitulo-zero",
		title: "Capitulo Zero",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/capitulo-zero.md",
		sourceLine: 8,
		searchText:
			"Capitulo Zero Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/capitulo-zero.md survival system-survival capitulo zero",
		tags: ["survival", "system-survival", "capitulo", "zero"],
	},
	{
		id: "system-survival-compendio-de-talentos",
		title: "Compendio De Talentos",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/compendio-de-talentos.md",
		sourceLine: 8,
		searchText:
			"Compendio De Talentos Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/compendio-de-talentos.md survival system-survival compendio de talentos",
		tags: ["survival", "system-survival", "compendio", "de", "talentos"],
	},
	{
		id: "system-survival-descanso-e-acampamento-completo",
		title: "Descanso E Acampamento Completo",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/descanso-e-acampamento-completo.md",
		sourceLine: 8,
		searchText:
			"Descanso E Acampamento Completo Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/descanso-e-acampamento-completo.md survival system-survival descanso e acampamento completo",
		tags: [
			"survival",
			"system-survival",
			"descanso",
			"e",
			"acampamento",
			"completo",
		],
	},
	{
		id: "system-survival-ficha-de-monstro",
		title: "Ficha De Monstro",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/ficha-de-monstro.md",
		sourceLine: 8,
		searchText:
			"Ficha De Monstro Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/ficha-de-monstro.md survival system-survival ficha de monstro",
		tags: ["survival", "system-survival", "ficha", "de", "monstro"],
	},
	{
		id: "system-survival-ficha-expandida",
		title: "Ficha Expandida",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/ficha-expandida.md",
		sourceLine: 8,
		searchText:
			"Ficha Expandida Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/ficha-expandida.md survival system-survival ficha expandida",
		tags: ["survival", "system-survival", "ficha", "expandida"],
	},
	{
		id: "system-survival-glossario-definitivo-de-testes",
		title: "Glossario Definitivo De Testes",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/glossario-definitivo-de-testes.md",
		sourceLine: 8,
		searchText:
			"Glossario Definitivo De Testes Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/glossario-definitivo-de-testes.md survival system-survival glossario definitivo de testes",
		tags: [
			"survival",
			"system-survival",
			"glossario",
			"definitivo",
			"de",
			"testes",
		],
	},
	{
		id: "system-survival-guia-criacao-de-ficha",
		title: "Guia Criacao De Ficha",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/guia-criacao-de-ficha.md",
		sourceLine: 8,
		searchText:
			"Guia Criacao De Ficha Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/guia-criacao-de-ficha.md survival system-survival guia criacao de ficha",
		tags: ["survival", "system-survival", "guia", "criacao", "de", "ficha"],
	},
	{
		id: "system-survival-indice-sistema",
		title: "Indice Sistema",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/indice-sistema.md",
		sourceLine: 8,
		searchText:
			"Indice Sistema Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/indice-sistema.md survival system-survival indice sistema",
		tags: ["survival", "system-survival", "indice", "sistema"],
	},
	{
		id: "system-survival-regras-0-hp-e-inconsciencia",
		title: "Regras 0 Hp E Inconsciencia",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/regras-0-hp-e-inconsciencia.md",
		sourceLine: 8,
		searchText:
			"Regras 0 Hp E Inconsciencia Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/regras-0-hp-e-inconsciencia.md survival system-survival regras ref-0 hp e inconsciencia",
		tags: [
			"survival",
			"system-survival",
			"regras",
			"ref-0",
			"hp",
			"e",
			"inconsciencia",
		],
	},
	{
		id: "system-survival-regras-bastiao",
		title: "Regras Bastiao",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/regras-bastiao.md",
		sourceLine: 8,
		searchText:
			"Regras Bastiao Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/regras-bastiao.md survival system-survival regras bastiao",
		tags: ["survival", "system-survival", "regras", "bastiao"],
	},
	{
		id: "system-survival-regras-completas-interacoes-sociais",
		title: "Regras Completas Interacoes Sociais",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/regras-completas-interacoes-sociais.md",
		sourceLine: 8,
		searchText:
			"Regras Completas Interacoes Sociais Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/regras-completas-interacoes-sociais.md survival system-survival regras completas interacoes sociais",
		tags: [
			"survival",
			"system-survival",
			"regras",
			"completas",
			"interacoes",
			"sociais",
		],
	},
	{
		id: "system-survival-regras-economia-quebra-criacao-itens",
		title: "Regras Economia Quebra Criacao Itens",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/regras-economia-quebra-criacao-itens.md",
		sourceLine: 8,
		searchText:
			"Regras Economia Quebra Criacao Itens Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/regras-economia-quebra-criacao-itens.md survival system-survival regras economia quebra criacao itens",
		tags: [
			"survival",
			"system-survival",
			"regras",
			"economia",
			"quebra",
			"criacao",
			"itens",
		],
	},
	{
		id: "system-survival-regras-fama-infamia-favor-faccoes",
		title: "Regras Fama Infamia Favor Faccoes",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/regras-fama-infamia-favor-faccoes.md",
		sourceLine: 8,
		searchText:
			"Regras Fama Infamia Favor Faccoes Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/regras-fama-infamia-favor-faccoes.md survival system-survival regras fama infamia favor faccoes",
		tags: [
			"survival",
			"system-survival",
			"regras",
			"fama",
			"infamia",
			"favor",
			"faccoes",
		],
	},
	{
		id: "system-survival-regras-furtividade-infiltracao",
		title: "Regras Furtividade Infiltracao",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/regras-furtividade-infiltracao.md",
		sourceLine: 8,
		searchText:
			"Regras Furtividade Infiltracao Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/regras-furtividade-infiltracao.md survival system-survival regras furtividade infiltracao",
		tags: [
			"survival",
			"system-survival",
			"regras",
			"furtividade",
			"infiltracao",
		],
	},
	{
		id: "system-survival-regras-habilidades-heroicas-ultimates-limit-break",
		title: "Regras Habilidades Heroicas Ultimates Limit Break",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile:
			"docs/system/survival/regras-habilidades-heroicas-ultimates-limit-break.md",
		sourceLine: 8,
		searchText:
			"Regras Habilidades Heroicas Ultimates Limit Break Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/regras-habilidades-heroicas-ultimates-limit-break.md survival system-survival regras habilidades heroicas ultimates limit break",
		tags: [
			"survival",
			"system-survival",
			"regras",
			"habilidades",
			"heroicas",
			"ultimates",
			"limit",
			"break",
		],
	},
	{
		id: "system-survival-regras-magia",
		title: "Regras Magia",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/regras-magia.md",
		sourceLine: 8,
		searchText:
			"Regras Magia Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/regras-magia.md survival system-survival regras magia",
		tags: ["survival", "system-survival", "regras", "magia"],
	},
	{
		id: "system-survival-regras-negociacao",
		title: "Regras Negociacao",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/regras-negociacao.md",
		sourceLine: 8,
		searchText:
			"Regras Negociacao Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/regras-negociacao.md survival system-survival regras negociacao",
		tags: ["survival", "system-survival", "regras", "negociacao"],
	},
	{
		id: "system-survival-regras-ouro-equipamento-inicial",
		title: "Regras de Ouro: Equipamento Inicial",
		category: "system-survival",
		summary:
			"Conversão: 1 Ouro (O) = 100 Prata (P) = 1000 Cobre (C). Ouro Nível 1: 1d10 x 10 Ouro (ou definido por Antecedente). Checklist de Equipamento: 1 Arma Primária, 1 Armadura, 1 Escudo/Secundária e Kit de Aventureiro.",
		sourceFile: "docs/system/survival/regras-ouro-equipamento-inicial.md",
		sourceLine: 7,
		searchText:
			"Regras de Ouro: Equipamento Inicial Conversão: 1 Ouro (O) = 100 Prata (P) = 1000 Cobre (C). Ouro Nível 1: 1d10 x 10 Ouro (ou definido por Antecedente). Checklist de Equipamento: 1 Arma Primária, 1 Armadura, 1 Escudo/Secundária e Kit de Aventureiro. docs/system/survival/regras-ouro-equipamento-inicial.md survival system-survival regras ouro equipamento inicial",
		tags: [
			"survival",
			"system-survival",
			"regras",
			"ouro",
			"equipamento",
			"inicial",
		],
	},
	{
		id: "system-survival-regras-peso-carga",
		title: "Regras de Logística: Peso e Carga",
		category: "system-survival",
		summary: "Limite = [Físico + Resistência] + 6 Slots.",
		sourceFile: "docs/system/survival/regras-peso-carga.md",
		sourceLine: 7,
		searchText:
			"Regras de Logística: Peso e Carga Limite = [Físico + Resistência] + 6 Slots. docs/system/survival/regras-peso-carga.md survival system-survival regras peso carga",
		tags: ["survival", "system-survival", "regras", "peso", "carga"],
	},
	{
		id: "system-survival-regras-pesquisa-lore-criptografia-linguas-antigas",
		title: "Regras Pesquisa Lore Criptografia Linguas Antigas",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile:
			"docs/system/survival/regras-pesquisa-lore-criptografia-linguas-antigas.md",
		sourceLine: 8,
		searchText:
			"Regras Pesquisa Lore Criptografia Linguas Antigas Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/regras-pesquisa-lore-criptografia-linguas-antigas.md survival system-survival regras pesquisa lore criptografia linguas antigas",
		tags: [
			"survival",
			"system-survival",
			"regras",
			"pesquisa",
			"lore",
			"criptografia",
			"linguas",
			"antigas",
		],
	},
	{
		id: "system-survival-retreino-e-recondicionamento",
		title: "Retreino E Recondicionamento",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/retreino-e-recondicionamento.md",
		sourceLine: 8,
		searchText:
			"Retreino E Recondicionamento Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/retreino-e-recondicionamento.md survival system-survival retreino e recondicionamento",
		tags: ["survival", "system-survival", "retreino", "e", "recondicionamento"],
	},
	{
		id: "system-survival-sistema-de-dividas-antes-depois",
		title: "Sistema De Dividas Antes Depois",
		category: "system-survival",
		summary:
			"Entrada de referencia do sistema Pandorha para consulta no Compendio.",
		sourceFile: "docs/system/survival/sistema-de-dividas-antes-depois.md",
		sourceLine: 8,
		searchText:
			"Sistema De Dividas Antes Depois Entrada de referencia do sistema Pandorha para consulta no Compendio. docs/system/survival/sistema-de-dividas-antes-depois.md survival system-survival sistema de dividas antes depois",
		tags: [
			"survival",
			"system-survival",
			"sistema",
			"de",
			"dividas",
			"antes",
			"depois",
		],
	},
] as const satisfies readonly CompendiumEntry[];
