import type { WorldTileRecord } from "./worldTileSchema";

const HEXCRAWL_SOURCE = "docs/system/survival/c-dex-de-hexcrawl-e-explora-o.md";

export const WORLD_TILE_CATALOG = [
	{
		id: "camp-road",
		label: "Estrada do Acampamento",
		q: 0,
		r: 0,
		biome: "road",
		regionTier: 1,
		isKnown: true,
		isMapped: true,
		isBlocked: false,
		encounterSignal: "none",
		sourceFile: HEXCRAWL_SOURCE,
		summary:
			"Ponto inicial mapeado para validar o movimento axial do hexcrawl de treino.",
	},
	{
		id: "north-pines",
		label: "Pinheiros do Norte",
		q: 0,
		r: -1,
		biome: "forest",
		regionTier: 1,
		isKnown: true,
		isMapped: false,
		isBlocked: false,
		encounterSignal: "none",
		sourceFile: HEXCRAWL_SOURCE,
		summary:
			"Hex ao norte usado para validar a primeira face do dado de desvio.",
	},
	{
		id: "northeast-watch",
		label: "Posto do Nordeste",
		q: 1,
		r: -1,
		biome: "watch",
		regionTier: 1,
		isKnown: true,
		isMapped: false,
		isBlocked: false,
		encounterSignal: "none",
		sourceFile: HEXCRAWL_SOURCE,
		summary:
			"Hex ao nordeste usado para validar vizinhanca axial sem mapa procedural.",
	},
	{
		id: "southeast-ruins",
		label: "Ruínas Baixas",
		q: 1,
		r: 0,
		biome: "ruins",
		regionTier: 2,
		isKnown: true,
		isMapped: false,
		isBlocked: false,
		encounterSignal: "check",
		sourceFile: HEXCRAWL_SOURCE,
		summary:
			"Ruinas de treino que apenas sinalizam encontro possivel, sem tabela real.",
	},
	{
		id: "south-marsh",
		label: "Charco do Sul",
		q: 0,
		r: 1,
		biome: "marsh",
		regionTier: 2,
		isKnown: false,
		isMapped: false,
		isBlocked: false,
		encounterSignal: "none",
		sourceFile: HEXCRAWL_SOURCE,
		summary:
			"Hex desconhecido usado para validar descoberta em memoria durante movimento.",
	},
	{
		id: "southwest-barrow",
		label: "Túmulo do Sudoeste",
		q: -1,
		r: 1,
		biome: "barrow",
		regionTier: 2,
		isKnown: true,
		isMapped: false,
		isBlocked: true,
		encounterSignal: "none",
		sourceFile: HEXCRAWL_SOURCE,
		summary:
			"Hex bloqueado para validar impedimento de travessia sem regra de terreno real.",
	},
	{
		id: "northwest-ridge",
		label: "Crista do Vento",
		q: -1,
		r: 0,
		biome: "ridge",
		regionTier: 1,
		isKnown: true,
		isMapped: false,
		isBlocked: false,
		encounterSignal: "none",
		sourceFile: HEXCRAWL_SOURCE,
		summary:
			"Hex ao noroeste usado para fechar a ordem oficial das seis direcoes.",
	},
] satisfies readonly WorldTileRecord[];
