import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const scriptPath = path.join(
	repoRoot,
	"scripts",
	"generate_compendium_catalog.mjs",
);

test("generates deterministic Compendium entries from system docs", async () => {
	const fixture = await createFixtureRoot();
	const opaqueHeading = [
		"0301",
		"Imunidades",
		"Resistencias",
		"e",
		"Vulnerabilidades.md",
	].join("");
	const outputPath = path.join(
		fixture,
		"src",
		"entities",
		"compendium",
		"model",
		"generatedCompendiumCatalog.ts",
	);

	try {
		await writeSystemDoc(
			fixture,
			"docs/system/survival/guia-de-teste.md",
			[
				"# Guia De Teste",
				"",
				"Resumo legivel de sobrevivencia para a busca do compendio.",
			].join("\n"),
		);
		await writeSystemDoc(
			fixture,
			"docs/system/combat/03-ataque-basico.md",
			[
				"# Ataque Basico",
				"",
				"Resumo legivel de combate para a busca do compendio.",
			].join("\n"),
		);
		await writeSystemDoc(
			fixture,
			"docs/system/combat/03-01-imunidades-resistencias-e-vulnerabilidades.md",
			[`# ${opaqueHeading}`, "", opaqueHeading].join("\n"),
		);
		await writeSystemDoc(
			fixture,
			"docs/system/magic/magia-basica.md",
			[
				"# Magia Basica",
				"",
				"Resumo legivel de magia para a busca do compendio.",
			].join("\n"),
		);
		await writeSystemDoc(
			fixture,
			"docs/system/survival/pandorha-sistema-compilado.md",
			["# Sistema Compilado", "", "Este arquivo duplicado nao entra."].join(
				"\n",
			),
		);

		const result = runGenerator(fixture, outputPath);

		assert.equal(result.status, 0, result.stderr);
		const content = await readFile(outputPath, "utf8");
		assert.match(
			content,
			/AUTO-GENERATED by scripts\/generate_compendium_catalog\.mjs/,
		);
		assert.match(content, /id: "system-survival-guia-de-teste"/);
		assert.match(content, /category: "system-survival"/);
		assert.match(content, /id: "system-combat-03-ataque-basico"/);
		assert.match(content, /category: "system-combat"/);
		assert.match(
			content,
			/tags: \["combat", "system-combat", "ref-03", "ataque", "basico"\]/,
		);
		assert.match(
			content,
			/title: "03 01 Imunidades Resistencias E Vulnerabilidades"/,
		);
		assert.doesNotMatch(content, new RegExp(opaqueHeading.replace(".", "\\.")));
		assert.match(content, /id: "system-magic-magia-basica"/);
		assert.match(content, /category: "system-magic"/);
		assert.doesNotMatch(content, /pandorha-sistema-compilado/);

		const secondResult = runGenerator(fixture, outputPath);
		assert.equal(secondResult.status, 0, secondResult.stderr);
		assert.equal(await readFile(outputPath, "utf8"), content);
	} finally {
		await rm(fixture, { recursive: true, force: true });
	}
});

test("strips metadata and ignored blocks before choosing a summary", async () => {
	const fixture = await createFixtureRoot();
	const outputPath = path.join(fixture, "generated.ts");

	try {
		await writeSystemDoc(
			fixture,
			"docs/system/magic/metamagia.md",
			[
				"---",
				"title: ignored",
				"---",
				"# Metamagia",
				"",
				"<ai_ignore>",
				"Este texto interno nao deve aparecer.",
				"</ai_ignore>",
				"",
				"<ai_context>",
				"Resumo visivel sem marcadores HTML.",
				"</ai_context>",
			].join("\n"),
		);

		const result = runGenerator(fixture, outputPath);

		assert.equal(result.status, 0, result.stderr);
		const content = await readFile(outputPath, "utf8");
		assert.match(content, /summary: "Resumo visivel sem marcadores HTML\."/);
		assert.doesNotMatch(content, /Este texto interno/);
		assert.doesNotMatch(content, /ai_context/);
	} finally {
		await rm(fixture, { recursive: true, force: true });
	}
});

test("check mode fails when the generated file is stale", async () => {
	const fixture = await createFixtureRoot();
	const outputPath = path.join(fixture, "generated.ts");

	try {
		await writeSystemDoc(
			fixture,
			"docs/system/combat/ataque.md",
			["# Ataque", "", "Resumo de ataque para o indice."].join("\n"),
		);
		const writeResult = runGenerator(fixture, outputPath);
		assert.equal(writeResult.status, 0, writeResult.stderr);
		await writeFile(outputPath, "stale\n", "utf8");

		const checkResult = runGenerator(fixture, outputPath, ["--check"]);

		assert.notEqual(checkResult.status, 0);
		assert.match(checkResult.stderr, /out of date/i);
	} finally {
		await rm(fixture, { recursive: true, force: true });
	}
});

async function createFixtureRoot() {
	return await mkdtemp(path.join(os.tmpdir(), "pandorha-compendium-"));
}

async function writeSystemDoc(root, relativePath, content) {
	const absolutePath = path.join(root, ...relativePath.split("/"));
	await mkdir(path.dirname(absolutePath), { recursive: true });
	await writeFile(absolutePath, `${content}\n`, "utf8");
}

function runGenerator(root, outputPath, extraArgs = []) {
	return spawnSync(
		process.execPath,
		[scriptPath, "--root", root, "--output", outputPath, ...extraArgs],
		{
			cwd: repoRoot,
			encoding: "utf8",
		},
	);
}
